package uk.gov.bis.lite.spire;

public interface SpireName {

  String VERSION_1_0 = "1.0";
  String VERSION_1_1 = "1.1";
  String SAR_XPATH_EXP = "//*[local-name()='RESPONSE']";

  // CREATE_OGEL_APP (COA)
  String COA_NAME_SPACE = "SPIRE_CREATE_OGEL_APP";
  String COA_REQUEST_CHILD = "OGEL_DETAILS";
  String COA_RESPONSE_ELEMENT = "SPIRE_REF";

  // CREATE_LITE_SAR (CLS)
  String CLS_NAME_SPACE = "SPIRE_CREATE_LITE_SAR";
  String CLS_REQUEST_CHILD = "SAR_DETAILS";
  String CLS_RESPONSE_ELEMENT = "SAR_REF";

  // CREATE_SITE_FOR_SAR (CSFS)
  String CSFS_NAME_SPACE = "SPIRE_CREATE_SITE_FOR_SAR";
  String CSFS_REQUEST_CHILD = "SITE_DETAILS";
  String CSFS_RESPONSE_ELEMENT = "SITE_REF";

  // EDIT_USER_ROLES (EUR)
  String EUR_NAME_SPACE = "SPIRE_EDIT_USER_ROLES";
  String EUR_REQUEST_CHILD = "USER_DETAILS";
  String EUR_RESPONSE_ELEMENT = "RESULT";

  // SPIRE_COMPANY_SITES
  String COMPANY_SITES_NAME_SPACE = "SPIRE_COMPANY_SITES";
  String COMPANY_SITES_REQUEST_CHILD = "getSites";
  String COMPANY_SITES_RESPONSE_LIST = "//COMPANY_SITE_LIST";

  // SPIRE_COMPANIES
  String COMPANIES_NAME_SPACE = "SPIRE_COMPANIES";
  String COMPANIES_REQUEST_CHILD = "getCompanies";
  String COMPANIES_RESPONSE_LIST = "//COMPANIES_LIST";

  String VERSION_NO = "VERSION_NO";
  String CUSTOMER_NAME = "CUSTOMER_NAME";
  String CUSTOMER_TYPE = "CUSTOMER_TYPE";
  String LITE_ADDRESS = "LITE_ADDRESS";
  String ADDRESS = "ADDRESS";
  String WUA_ID = "WUA_ID";
  String COUNTRY_REF = "COUNTRY_REF";
  String WEBSITE = "WEBSITE";

  String SAR_REF = "SAR_REF";
  String SITE_REF = "SITE_REF";
  String DIVISION = "DIVISION";

  String COMPANY_NAME = "COMPANY_NAME";
  String APPLICANT_TYPE = "APPLICANT_TYPE";
  String OCCUPANCY_STATUS = "OCCUPANCY_STATUS";

  String REFERENCE = "REFERENCE";
  String NAME = "NAME";
  String SHORT_NAME = "SHORT_NAME";
  String ORGANISATION_TYPE = "ORGANISATION_TYPE";
  String COMPANY_NUMBER = "COMPANY_NUMBER";
  String REGISTRATION_STATUS = "REGISTRATION_STATUS";
  String REGISTERED_ADDRESS = "REGISTERED_ADDRESS";
  String NATURE_OF_BUSINESS = "NATURE_OF_BUSINESS";
  String COUNTRY_OF_ORIGIN = "COUNTRY_OF_ORIGIN";
  String WEBSITE_LIST = "WEBSITE_LIST";
  String WEBSITE_URL = "URL";
  String WEBSITE_ACTION = "ACTIONS";

  String ADMIN_WUA_ID = "ADMIN_WUA_ID";
  String USER_WUA_ID = "USER_WUA_ID";
  String ROLE_TYPE = "ROLE_TYPE";

  String userId = "userId";
  String sarRef = "sarRef";
  String orgRef = "orgRef";
  String companyName = "companyName";
  String companyNumber = "companyNumber";
  String emailAddress = "emailAddress";
  String eoriNumber = "eoriNumber";
  String postCode = "postCode";

  String OGL_TYPE_LIST = "OGL_TYPE_LIST";
  String OGL_TYPE = "OGL_TYPE";
  String TYPE = "TYPE";

  String COMPANIES_HOUSE_NUMBER = "COMPANIES_HOUSE_NUMBER";
  String COMPANIES_HOUSE_VALIDATED = "COMPANIES_HOUSE_VALIDATED";
  String EORI_NUMBER = "EORI_NUMBER";
  String EORI_VALIDATED = "EORI_VALIDATED";
}
