DROP TABLE LOCAL_OGEL_SUBMISSION;

CREATE TABLE IF NOT EXISTS LOCAL_OGEL_SUBMISSION (
  ID                INTEGER PRIMARY KEY AUTOINCREMENT,
  USER_ID           TEXT,
  ADMIN_USER_ID     TEXT,
  OGEL_TYPE         TEXT,
  MODE              TEXT,
  STAGE             TEXT,
  STATUS            TEXT,
  CALLED_BACK       BOOLEAN,
  CUSTOMER_REF      TEXT,
  SITE_REF          TEXT,
  SPIRE_REF         TEXT,
  ROLE_UPDATE       BOOLEAN,
  ROLE_UPDATED      BOOLEAN,
  FAIL_REASON       TEXT,
  SUBMISSION_REF    TEXT,
  CALLBACK_URL      TEXT,
  FIRST_FAIL        DATETIME,
  LAST_FAIL_MESSAGE TEXT,
  JSON              TEXT,
  CREATED           DATETIME            DEFAULT CURRENT_TIMESTAMP
);