/*
 * Ogel Registration DB Script
 */
CREATE TABLE IF NOT EXISTS LOCAL_OGEL_REGISTRATION (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  LITE_ID TEXT,
  OGEL_TYPE TEXT,
  USER_ID TEXT,
  CUSTOMER_ID TEXT,
  SITE_ID TEXT,
  STATUS TEXT,
  CREATED DATETIME DEFAULT CURRENT_TIMESTAMP);