/*
 * Ogel Registration DB Script
 */
CREATE TABLE IF NOT EXISTS LOCAL_OGEL_SUBMISSION (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  USER_ID TEXT,
  OGEL_TYPE TEXT,
  STATUS TEXT,
  SUBMISSION_REF TEXT,
  CUSTOMER_REF TEXT,
  SITE_REF TEXT,
  SPIRE_REF TEXT,
  ROLE_UPDATE BOOLEAN,
  JSON TEXT,
  CREATED DATETIME DEFAULT CURRENT_TIMESTAMP);