/*
 * Ogel Submission DB Script
 */
CREATE TABLE IF NOT EXISTS LOCAL_OGEL_SUBMISSION (
  ID                INTEGER PRIMARY KEY AUTOINCREMENT,
  USER_ID           TEXT,
  OGEL_TYPE         TEXT,
  MODE              TEXT,
  STATUS            TEXT,
  SUBMISSION_REF    TEXT,
  CUSTOMER_REF      TEXT,
  SITE_REF          TEXT,
  SPIRE_REF         TEXT,
  FIRST_FAIL        DATETIME,
  LAST_FAIL_MESSAGE TEXT,
  CALLBACK_URL      TEXT,
  CALLED_BACK       BOOLEAN,
  ROLE_UPDATE       BOOLEAN,
  ROLE_UPDATED      BOOLEAN,
  JSON              TEXT,
  CREATED           DATETIME            DEFAULT CURRENT_TIMESTAMP
);