package uk.gov.bis.lite.spireclient;

public interface SpireNames {

  String SAR_XPATH_EXP_RESPONSE = "//*[local-name()='RESPONSE']";
  String SAR_XPATH_EXP_FAULT = "//*[local-name()='FAULT']";

  // SPIRE_CREATE_OGEL_APP (COA)
  String COA_NAME_SPACE = "SPIRE_CREATE_OGEL_APP";
  String COA_ENDPOINT = "CREATE_OGEL_APP";
  String COA_REQUEST_CHILD = "OGEL_DETAILS";
  String COA_RESPONSE_ELEMENT = "SPIRE_REF";

  // SPIRE_CREATE_LITE_SAR (CLS)
  String CLS_NAME_SPACE = "SPIRE_CREATE_LITE_SAR";
  String CLS_ENDPOINT = "CREATE_LITE_SAR";
  String CLS_REQUEST_CHILD = "SAR_DETAILS";
  String CLS_RESPONSE_ELEMENT = "SAR_REF";

  // SPIRE_CREATE_SITE_FOR_SAR (CSFS)
  String CSFS_NAME_SPACE = "SPIRE_CREATE_SITE_FOR_SAR";
  String CSFS_ENDPOINT = "CREATE_SITE_FOR_SAR";
  String CSFS_REQUEST_CHILD = "SITE_DETAILS";
  String CSFS_RESPONSE_ELEMENT = "SITE_REF";

  // SPIRE_EDIT_USER_ROLES (EUR)
  String EUR_NAME_SPACE = "SPIRE_EDIT_USER_ROLES";
  String EUR_ENDPOINT = "EDIT_USER_ROLES";
  String EUR_REQUEST_CHILD = "USER_DETAILS";
  String EUR_RESPONSE_ELEMENT = "RESULT";

  String VERSION_NO = "VERSION_NO";
  String CUSTOMER_NAME = "CUSTOMER_NAME";
  String CUSTOMER_TYPE = "CUSTOMER_TYPE";
  String LITE_ADDRESS = "LITE_ADDRESS";
  String ADDRESS = "ADDRESS";
  String WUA_ID = "WUA_ID";
  String COUNTRY_REF = "COUNTRY_REF";
  String WEBSITE = "WEBSITE";

  String SAR_REF = "SAR_REF";
  String SITE_REF = "SITE_REF";
  String DIVISION = "DIVISION";

  String ADMIN_WUA_ID = "ADMIN_WUA_ID";
  String USER_WUA_ID = "USER_WUA_ID";
  String ROLE_TYPE = "ROLE_TYPE";

  String OGL_TYPE_LIST = "OGL_TYPE_LIST";
  String OGL_TYPE = "OGL_TYPE";
  String TYPE = "TYPE";

  String COMPANIES_HOUSE_NUMBER = "COMPANIES_HOUSE_NUMBER";
  String COMPANIES_HOUSE_VALIDATED = "COMPANIES_HOUSE_VALIDATED";
  String EORI_NUMBER = "EORI_NUMBER";
  String EORI_VALIDATED = "EORI_VALIDATED";

}
